# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  main_config = debug
  occupations_config = debug
endif
ifeq ($(config),release)
  main_config = release
  occupations_config = release
endif

PROJECTS := main occupations

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

main:
ifneq (,$(main_config))
	@echo "==== Building main ($(main_config)) ===="
	@${MAKE} --no-print-directory -C main/build -f main.make config=$(main_config)
endif

occupations:
ifneq (,$(occupations_config))
	@echo "==== Building occupations ($(occupations_config)) ===="
	@${MAKE} --no-print-directory -C main/build -f occupations.make config=$(occupations_config)
endif

clean:
	@${MAKE} --no-print-directory -C main/build -f main.make clean
	@${MAKE} --no-print-directory -C main/build -f occupations.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   main"
	@echo "   occupations"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"